name: --pre Test
# An "early warning" cron job that will install dependencies
# with `pip install --pre` periodically to test for breakage
# (and open an issue if a test fails)

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours
  workflow_dispatch:

jobs:

  test:
    name: ${{ matrix.platform }} (${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        platform: [macos-latest, windows-latest]
        backend: [pyside2, pyqt5]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install --pre -e .[test,${{ matrix.backend }}]

      - name: Install Micro-Manager
        if: runner.os == 'Windows'
        run: python -m pymmcore_plus.install

      - name: Install Micro-Manager
        if: runner.os == 'macOS'
        # need to figure out what happened on mac with the utilities
        run: python -m pymmcore_plus.install -r 20220420

      - name: Test
        run: pytest -v --cov=pymmcore_widgets --cov-report=xml --color=yes

      # If something goes wrong, we can open an issue in the repo
      - name: Report Failures
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLATFORM: ${{ matrix.platform }}
          PYTHON: ${{ matrix.python }}
          RUN_ID: ${{ github.run_id }}
          TITLE: '[test-bot] pip install --pre is failing'
        with:
          filename: .github/TEST_FAIL_TEMPLATE.md
          update_existing: true
